== Datasets Recommended for the Code Sprint

For demonstration purposes, participants are encouraged to download the following datasets and to configure their implementations of OGC APIs to publish data and maps for the following Areas of Interest (AOI):

* Europe: The area around Bournemouth, England, within the extent specified by this https://github.com/opengeospatial/ogcapi-code-sprint-2021-05/blob/main/BournemouthAOI.geojson[GeoJSON file] or this WKT string in *EPSG:4326* coordinates `POLYGON ((-2.13384466616954 50.5343261657655,-2.14712951953212 50.822458640394,-1.77636133932212 50.8243659606517,-1.75884948716236 50.539699354356,-2.13384466616954 50.5343261657655))`.
* North America: Red River of the North, within the extent specified by this https://github.com/opengeospatial/ogcapi-code-sprint-2021-05/blob/main/RedRiverAOI.geojson[GeoJSON file] or this WKT string in *EPSG:4326* coordinates `POLYGON ((-97.8656275465241 50.1994331527875,-97.8290574091464 48.9215621457706,-96.475962326173 48.9305725567791,-96.4851048605174 50.2082107872824,-97.8656275465241 50.1994331527875))`.

=== Ordnance Survey

==== OS Open Zoomstack

Sprint participants are encouraged to use *OS Open Zoomstack*, a comprehensive basemap of the United Kingdom showing coverage from national level right down to street detail.

https://os.uk/business-government/products/open-zoomstack

Stylesheets (including OGC SLD, Esri LYR, QGIS QML and Mapbox GL Styles) https://github.com/OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets

==== OS Boundary-Line and OS Open GreenSpace

Vector tiles of Boundary-Line, OS Open GreenSpace, Rivers and Roads are all available to download for free from the https://osdatahub.os.uk[Ordnance Survey Data Hub].

Any sprint participants are free to sign up to the Data Hub to use any of Ordnance Survey's APIs as well (e.g. participants could implement an OGC API proxy in front to translate from WMTS etc.).


=== Natural Resources Canada

==== High-Resolution Digital Elevation Model (HRDEM) from NRCan's Open Maps

Open Maps provides access to the Government of Canada’s geospatial information.

https://open.canada.ca/en/open-maps

HRDEM https://open.canada.ca/data/en/dataset/957782bf-847c-4644-a757-e383c0057995

=== Meteorological Service of Canada

==== MSC Open data

The available open data from the Meteorological Service of Canada provides up-to-date
information on past, present and future weather, water, climate and environmental
conditions over Canada and the world

https://eccc-msc.github.io/open-data
