== Datasets Recommended for the Code Sprint

For demonstration purposes, participants are encouraged to download the following datasets and to configure their implementations of OGC APIs to publish data and maps for the following Areas of Interest (AOI):

* Europe: TBA
* North America: Red River of the North, within the extent specified by this https://github.com/opengeospatial/ogcapi-code-sprint-2021-05/blob/main/RedRiverExtent.gpkg[GeoPackage] or this WKT string in WGS 84 coordinates `POLYGON ((-97.8656275465241 50.1994331527875,-97.8290574091464 48.9215621457706,-96.475962326173 48.9305725567791,-96.4851048605174 50.2082107872824,-97.8656275465241 50.1994331527875))`.

=== Ordnance Survey

==== OS Open Zoomstack

Sprint participants are encouraged to use *OS Open Zoomstack*, a comprehensive basemap of the United Kingdom showing coverage from national level right down to street detail.

https://os.uk/business-government/products/open-zoomstack

Stylesheets (including OGC SLD, Esri LYR, QGIS QML and Mapbox GL Styles) https://github.com/OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets

==== OS Boundary-Line and OS Open GreenSpace

Vector tiles of Boundary-Line, OS Open GreenSpace, Rivers and Roads are all available to download for free from the https://osdatahub.os.uk[Ordnance Survey Data Hub].

Any sprint participants are free to sign up to the Data Hub to use any of Ordnance Survey's APIs as well (e.g. participants could implement an OGC API proxy in front to translate from WMTS etc.).


=== Natural Resources Canada

==== High-Resolution Digital Elevation Model (HRDEM) from NRCan's Open Maps

Open Maps provides access to the Government of Canada’s geospatial information.

https://open.canada.ca/en/open-maps

HRDEM https://open.canada.ca/data/en/dataset/957782bf-847c-4644-a757-e383c0057995
