= Immediate Lessons and Next Steps

== Immediate Lessons

* The Tiles API is reasonably stable. We have seen different interpretations of how to apply styles to collections maps and the dataset maps.
* Evolution of WKSS into common TMS (the ones that are going to be registered). The evolution has taken us to a conclusion that WKSS.
* The concept of buildings blocks has been completely demonstrated. The three APIs have been successfully demonstrated together.
* The sprint has shown that a lot that is common can be shared across the APIs i.e. how much OGC API - Common - Part 2 facilitates the client implementation.
* The interaction between Maps, Tiles, Styles worked well. No major issues came up that could not be verified.
* More work needs to be done on Styles in general. e.g. where we use the styles has an impact on the resources.
* We focused on the API aspects of the styles but not on the formats of the styles. More work is needed on the formats aspects of the styles (e.g. SymCore).
* TBA
* TBA
* TBA

== Implications for the needs of NMAs

What will the APIs do to help meet the following needs?

* Providing the public with access to geospatial data and maps
* Facilitating analytics
* Reducing barriers to accessing geospatial data

== Next steps

How will the sprint’s outcomes will be incorporated into future OGC Standards Program and Innovation Program activities?

=== Next Steps for the Innovation Program

* TBA

=== Next Steps on the Standards Program

* TBA
* TBA
