==== EarthPulse

EarthPulse is an SME which operates within the fields of data engineering and data analytics. Its staff are experts in the areas of data analytics, full-stack development, Big Data, product development and access, management and processing of data sources such as geospatial or textual data.

EarthPulse is commited to Free and Open Source software (FOSS) and open standards.

https://github.com/doublebyte1/[@doublebyte1] and https://github.com/PascalLike[@PascalLike] have participated in this sprint. 

===== Motivation to Participate

We are participating in an H2020 research project (945307 - eMOTIONAL Cities), and our main task is to create a spatial data infrastructure, using modern technologies.

Our main motivation to participate in this sprint was to learn more about the OGC API standards and its current implementations, to assess what is feasible to adopt in the project. At the same time, we wanted to contribute to testing (and eventually improving) of current OGC API implementations.

===== Implemented Solution

In this sprint we decided to focus on the OGC API Tiles specification. In order to get familiar with it, we decided to test some of its implementations.

We started by installing and deploying the https://pygeoapi.io/[pygeoapi], and we configured it to use our neuroscience dataset:

http://ec2-3-65-14-187.eu-central-1.compute.amazonaws.com:5000/

During this process we become aware of a bug on the OpenAPI representation of the get tile request.

A PR was created to address this issue (already merged to the core):

https://github.com/geopython/pygeoapi/pull/694

We also became aware of an https://github.com/geopython/pygeoapi/issues/567[issue] with the default background map on the example configuration file. It was addressed on this PR:

https://github.com/geopython/pygeoapi/pull/697#partial-pull-merging

Finally, we tested the OGC API Tiles implementation of the spec, using postman:

https://www.getpostman.com/collections/3c54a654cb74f803b683

We believe that not all the OGC API Vector tiles requests are implemented, in particular in what regards TileMatrixSets. It seems difficult to retrieve a tile, when there are no requests to retrieve the TileMatrixSet.

We also wanted to check a client-side implementation of the spec, and came across https://github.com/frontiersi/leaflet-ogc-layers[this] repository, developed during this sprint.

On https://github.com/PascalLike/leaflet-ogc-layers[this] fork, we created an interactive map which uses this leaflet implementation:

http://ec2-3-65-14-187.eu-central-1.compute.amazonaws.com/


===== Proposed Alternatives

TBA

===== Experiences with OGC API Specifications

Our overall feeling, as final users, is that it is still hard to find server and client implementations that can talk to each other.

For instance, maybe one server side application may implement one building block, while a client application may implement another building block.

This issue will tend to vanish as support for more buidling blocks is added to the applications, or when a wider number of implementations of the OGC API become available.