== Subject

The subject of this Engineering Report (ER) is a code sprint that was held from 26 to 28 May 2021 to advance the development of the OGC API - Maps draft standard, OGC API - Tiles draft standard, and the OGC API – Styles draft standard. An Application Programming Interface (API) is a standard set of documented and supported functions and procedures that expose the capabilities or data of an operating system, application or service to other applications (adapted from ISO/IEC TR 13066-2:2016). The code sprint was hosted online. The code sprint was sponsored by Ordnance Survey (OS) and Natural Resources Canada (NRCan).

== Executive Summary

This Engineering Report (ER) summarizes the main achievements of the May 2021 OGC API Virtual Code Sprint, conducted between May 26 – 28, 2021. The goal of the code sprint was to progress the development of the draft OGC API standards for Maps, Tiles and Styles. The sprint also sought to help to identify issues and options for addressing those issues.

The objectives of the code sprint were to:

* Develop prototype implementations of OGC API – Maps
* Develop prototype implementations of OGC API – Tiles
* Develop prototype implementations of OGC API – Styles
* Test the prototype implementations
* Provide feedback to the Editor about what worked and what did not work
* Provide feedback about the specification document, especially what is missing from the document

Part of the motivation for holding the sprint was:

* APIs have proven to be a popular and a very effective enabler of rapid software development
* There is an increasing need for optimizing geospatial interoperability between Web APIs
* There is phenomenal adoption of location-handling capabilities in software within and outside of geospatial developer communities

The draft OGC API – Maps specification describes an API that presents data as maps by applying a style. The draft specification enables a client application to request maps as images. This includes the ability to specify or change parameters such as the size of an image and coordinate reference systems at the time of request.

The draft OGC API – Tiles specification describes an API building block that can enable other OGC API implementations to serve maps or tiled feature data divided into individual tiles. The draft specification includes concepts such as tile matrix sets and tile schemes. The draft standard can be used to publish map tiles and tiled feature data (e.g. GeoJSON Vector Tiles and Mapbox Vector Tiles).

The draft OGC API – Styles specification defines a Web API that enables map servers, clients as well as visual style editors, to manage and fetch styles that consist of symbolizing instructions that can be applied by a rendering engine on features and/or coverages.

The code sprint facilitated the development and testing of prototype implementations of the OGC API - Maps draft standard, OGC API - Tiles draft standard, and the OGC API – Styles draft standard. The code sprint therefore successfully met all of its objectives and achieved its goal of progressing the development of the draft OGC API standards for Maps, Tiles and Styles.

=== Summary of Outcomes

The outcomes and findings of the sprint can be summarized as follows:

* The Tiles API was found to be reasonably stable. However, there appears to be different interpretations of how to apply styles to maps collections and maps of datasets.
* Evolution of the Well Known Scale Set (WKSS) concept into common Tile Matrix Set (TMS) concepts was another outcome. The sprint participants suggested that information provided by WKSS could be derived from a TMS. Further consultation with other OGC Working Groups will be needed to determine the future role of WKSS in the 2D TMS Standard.
* Another key outcome is that interoperability of buildings blocks has been completely demonstrated. The three APIs have been successfully demonstrated together.
* The sprint has shown that a lot that is common can be shared across the APIs i.e. how much OGC API - Common - Part 2 facilitates the client implementation.
* The interaction between OGC APIs for Maps, Tiles, Styles worked well. No major issues came up that could not be verified and/or resolved.
* More work needs to be done on the Styles API in general. e.g. to determine the impact on API resources when styles are used.
* The code sprint focused on the API aspects of the styles but not on the formats of the styles. More work is needed on the format aspects of the styles (e.g. in relation to the https://docs.ogc.org/is/18-067r3/18-067r3.html[Symbology Core] standard).
* While in the Tiles API a metadata model has been developed, in the Maps API there has been less interest in developing a specific metadata model.

The sprint participants considered what the APIs will do to help meet the needs of the National Mapping Agency (NMA) community. The following is a summary:

* *Providing the public with access to geospatial data and maps*: The OGC APIs will make it easier for the general public to access maps through regular web browser technologies. For example, through OGC API - Maps it is now possible to access a complete map through a basic URL (i.e. no query parameters). OGC API - Tiles will make it easier to publish maps as tiled feature data (colloquially named 'vector tiles'), which are becoming increasingly popular in the NMA community. The APIs are able to provide data in a way that 2.5D and 3D visualization clients are able to handle.
* *Facilitating analytics*: OGC API - Tiles is able to publish tiled coverage data in such a way that makes it easier to 'stream' coverages for analysis at the screen resolution. This makes it possible to create histograms, vegetation indices, and other analytical reports all at the screen resolution. The flexibility of specifying the origin of the tiles will make it easier to combine regular OGC tiles with other tiles.
* *Reducing barriers to accessing geospatial data*: OGC APIs together make it easier to start with a dataset and then find a way to generate tiles and other resources. The OGC APIs are integrated in a very convenient way. The Styles API makes it possible for NMA's to publish styles from a central location in a way that is consistent with how they publish data. The integrated environment makes it easier to manage things together.

=== Plan outlining how the sprint's outcomes will be incorporated into future OGC activities

The following is a plan outlining how the sprint's outcomes will be presented to the OGC Standards Program and Innovation Program for potential consideration for future activities.

==== Potential activities for the Innovation Program

For the OGC Innovation Program, the sprint participants identified a need to:

* experiment with multidimensional data support in OGC APIs.
* explore how to turn legends into real data (objects) that can be combined by the client (e.g. asking a client to provide the elements that are in a legend).
* research how simple a structure needs to be to meet the needs for a legend while also being easily implementable.
* experiment with coverage tiles, as they are becoming increasingly important (e.g. in support of rendering a Digital Surface Model (DSM)).  Strategies for identifying suitable sizes of the tiles needs to tested/researched.
* experiment with non-grid coverages (e.g. point clouds).
* explore the possibility of an 'info' capability that supports different data sources and query options (not just retrieval of the value at a point).

OGC Innovation Program activities rely on sponsorship to resource initiatives. Therefore, the potential activities listed above will be presented to the OGC Technical Committee through the Architecture Domain Working Group in order to raise interest from potential sponsors.

==== Potential activities for the Standards Program

For the OGC Standards Program, the sprint participants identified a need to:

* specify a legend conformance class for the OGC API - Maps and OGC API - Tiles draft specifications.
* specify an 'info' conformance class for the OGC API - Maps and OGC API - Tiles  draft specifications.
* implement an OGC API - Maps conformance class/extension to support time dependent maps (in a way similar to the https://portal.ogc.org/files/?artifact_id=56394[OGC Best Practice for using Web Map Services (WMS) with Time-Dependent or Elevation-Dependent Data (1.0)]) e.g. the `subset` and `datetime` parameters.

The OGC API - Maps and OGC API - Tiles Standards Working Groups will be tasked with specifying requirements for the legend and info conformance classes. Once the requirements have been specified, there may be a need to conduct further experimentation focusing on implementations of the legend and info conformance classes.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization | Role
|Gobe Hobona | Open Geospatial Consortium | Editor
|	Adrian Alvarez	|	APCO	|	Contributor
|	Pelle Arvinder	|	Carmenta AB	|	Contributor
|	Nelio Matos	|	Connected Places Catapult	|	Contributor
|	Gaj Bala	|	CRTC	|	Contributor
|	Panagiotis (Peter) Vretanos	|	CubeWerx Inc.	|	Contributor
|	Keith Pomakis	|	CubeWerx Inc.	|	Contributor
|	Tino Kastbjerg Stigsen	|	Danish Defense	|	Contributor
|	Yasser Othman	|	EAD	|	Contributor
|	Joana Simoes	|	EarthPulse	|	Contributor
|	Antonio Cerciello	|	EarthPulse	|	Contributor
|	Diego Caraffini	|	Ecere Corporation	|	Contributor
|	Patrick Dion	|	Ecere Corporation	|	Contributor
|	Jerome St-Louis	|	Ecere Corporation	|	Contributor
|	James Munroe	|	Elemental Earth Data Ltd.	|	Contributor
|	Hisham Massih	|	Esri	|	Contributor
|	Anne Fitz	|	Esri	|	Contributor
|	Richie Carmichael	|	Esri	|	Contributor
|	Adewale Shittu	|	Federal University of Technology Akure 	|	Contributor
|	Serge Lévesque	|	Fisheries and Oceans Canada	|	Contributor
|	Rowan Winsemius	|	FrontierSI	|	Contributor
|	Jeff McKenna	|	GatewayGeo	|	Contributor
|	Francesco Bartoli	|	Geobeyond Srl	|	Contributor
|	Paul van Genuchten	|	GeoCat BV	|	Contributor
|	Gérald Fenoy	|	GeoLabs	|	Contributor
|	Andrea Aime	|	GeoSolutions	|	Contributor
|	Oscar Díaz	|	GeoSolutions	|	Contributor
|	Susie Mielby	|	Geus	|	Contributor
|	Nazih Fino	|	Global Nomad GIS Services	|	Contributor
|	Sara Gholamian	|	Gozar_e No	|	Contributor
|	Charles Heazel	|	Heazeltech	|	Contributor
|	Clemens Portele	|	interactive instruments GmbH	|	Contributor
|	Muhammed Mete	|	İstanbul Technical University	|	Contributor
|	Berke Şentürk	|	ITU	|	Contributor
|	Zack Zhang	|	JLL	|	Contributor
|	Lorena Hernández	|	European Commission - Joint Research Centre	|	Contributor
|	Bryan Evans	|	Kinder Institute at Rice University	|	Contributor
|	Chris Gagnon	|	Kongsberg Geospatial	|	Contributor
|	Eric Tse	|	Lexco Limited	|	Contributor
|	Philippe Pinheiro	|	Luxembourg Institute of Science and Technology	|	Contributor
|	Rajveer Shekhawat	|	Manipal University Jaipur	|	Contributor
|	Tom Kralidis	|	Meteorological Service of Canada	|	Contributor
|	Gonzalo Nogueras	|	MetOffice	|	Contributor
|	Ali Chettih	|	Montefiore IT	|	Contributor
|	Cameron Wilson	|	Natural Resources Canada	|	Contributor
|	Ryan Ahola	|	Natural Resources Canada	|	Contributor
|	Ahmed Ragab	|	Natural Resources Canada	|	Contributor
|	Azadeh Ashoori	|	Natural Resources Canada	|	Contributor
|	Pradeep Alva	|	National University of Singapore	|	Contributor
|	Bruno Kinoshita	|	NIWA	|	Contributor
| Scott Simmons | Open Geospatial Consortium | Contributor
| Scott Serich | Open Geospatial Consortium | Contributor
|	Angelos Tzotsos	|	Open Source Geospatial Foundation	|	Contributor
|	Michael Gordon	|	Ordnance Survey	|	Contributor
|	Chris Holmes	|	Planet	|	Contributor
|	Tim Schaub	|	Planet	|	Contributor
|	Basile Goussard	|	Promethee	|	Contributor
|	Tarron Newman	|	Red Helmet Technology	|	Contributor
|	Senthil Rajrndran	|	RMSI Pvt Ltd 	|	Contributor
|	Yohann Hazan	|	SDIS33	|	Contributor
|	Darrel Ronald	|	Spatiomatics	|	Contributor
|	Davince Koyo	|	Synergetic systems	|	Contributor
|	Núria Julià Selvas	|	Universitat Autònoma de Barcelona (CREAF)	|	Contributor
|	Joan Maso	|	Universitat Autònoma de Barcelona (CREAF)	|	Contributor
|	Ingrid Santana	|	UFMG	|	Contributor
|	Matthew Walker	|	UK Defence Science and Technology Laboratory	|	Contributor
|	Paul Walsh	|	UK Defence Science and Technology Laboratory	|	Contributor
|	Nick Bennett	|	UK Defence Science and Technology Laboratory	|	Contributor
|	Jonathan Lewis	|	UK Hydrographic Office	|	Contributor
|	Pablo Zader	|	UNC	|	Contributor
|	Andres Herrera	|	Univalle	|	Contributor
|	Joseph Olusina	|	University of Lagos	|	Contributor
|	Amy Youmans	|	US Army Geospatial Center	|	Contributor
|	Jeff Harrison	|	US Army Geospatial Center	|	Contributor
|	Huajun Zhang	|	US Census	|	Contributor
|	Ujjwal Yadav	|	Uttar Pradesh Remote Sensing Application Center 	|	Contributor
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
